version: 0.2
env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME : /myapp/docker-credentials/user-name
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
phases:
  install:
    runtime-versions:
      python : 3.11
  pre_build:
    commands:
      - pip install -r sample-flask-app/requirements.txt
      
  build:
    commands:
      - cd sample-flask-app
      - echo "Building docker image"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/sample-flask-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/sample-flask-app:latest"
  post_build:
    commands:
      - echo "Build is successful"